quotes/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('quoffee.quotes.views',
	url(r'^api/quotes/insert/', 'insert_quote', name='insert_quote'),
	url(r'^api/quotes/delete/', 'delete_quote', name='delete_quote'),
	url(r'^api/quotes/requote/', 'requote', name='requote'),
	url(r'^api/quotes/change-notebook/', 'change_notebook', name='change_notebook'),
	url(r'^api/quotes/get/index', 'get_index_quotes', name='get_index_quotes'),
	url(r'^q/(?P<uniquekey>\w+)/', 'get_quote_page', name='get_quote_page'),
	url(r'^quote/get/', 'get_quote_card', name='get_quote_card'),
	url(r'^quotes/get/', 'get_quote_data', name='get_quote_data'),
	url(r'^notebooks/get/', 'get_notebook_list', name='get_notebook_list'),
	url(r'^api/notebooks/(?P<action>\w+)/', 'notebook_crud', name='notebook_crud'),

)

urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView, TemplateView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from quoffee.views import SupportPageView, ContactPageView
from quoffee.users.views import user_home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'quoffee.quotes.views.index', name='index'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/app/app-logo-iDevice-greenbg.png')),
    url(r'^apple-touch-icon-precomposed\.png$', RedirectView.as_view(url='/static/images/app/app-logo-iDevice-greenbg.png')),
    url(r'^apple-touch-icon\.png$', RedirectView.as_view(url='/static/images/app/app-logo-iDevice-greenbg.png')),
    # url(r'^quoffee/', include('quoffee.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'quoffee.users.views.login'),
    url(r'^logout/$', 'quoffee.users.views.logout'),
    url(r'^bookmarklet/$', 'quoffee.quotes.views.bookmarklet_page'),
    url(r'^support/$', SupportPageView.as_view()),
    url(r'^contact/$', ContactPageView.as_view()),
    url(r'^complete-registration/$', 'quoffee.users.views.require_email', name='require_email'),

    url('', include('quoffee.context.urls', namespace='context')),
    url('', include('quoffee.quotes.urls', namespace='quotes')),
    url('', include('quoffee.users.urls', namespace='users')),
    url('', include('quoffee.notifications.urls', namespace='users')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^(?P<username>\w+)/$', user_home, name='user_home'),
)

users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('quoffee.users.views',
	url(r'^api/search/profiles/', 'search_profile', name='search_profile'),
	url(r'^user/activation/', 'user_activation', name='user_activation'),
	url(r'^(?P<username>\w+)/nb/(?P<notebook>\w+)/$', 'user_notebook', name='user_notebook'),
	url(r'^(?P<username>\w+)/tags/(?P<slug>[-\w]+)/$', 'user_tags', name='user_tags'),
)

quotes/models.py
from rest_framework import serializers
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from quoffee.context.models import Author, Category
from quoffee.notifications.models import Notification

# Create your models here.
class Notebook(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(max_length=100)
	uniquekey = models.CharField(max_length=4)

class Quote(models.Model):
	user = models.ForeignKey(User)
	uniquekey = models.CharField(max_length=32)
	text = models.TextField()
	author = models.ForeignKey(Author, null=True, blank=True)
	category = models.ForeignKey(Category, null=True, blank=True)
	custom_category = models.CharField(max_length=100, null=True, blank=True) # for custom categories only.
	requoted = models.BooleanField(default=False)
	requote_count = models.IntegerField(null=True, blank=True,default=0)
	added_date = models.DateTimeField(auto_now_add=True)
	deleted = models.BooleanField(default=False)
	notebook = models.ForeignKey(Notebook)
	meta = models.TextField(null=True, blank=True)
	url = models.CharField(max_length=150, null=True, blank=True)
	

class ReQuote(models.Model):
	quote = models.ForeignKey(Quote)
	user = models.ForeignKey(User) #user that requoted the quote.
	requote_date = models.DateTimeField(auto_now_add=True)
	deleted = models.BooleanField(default=False)
	requote = models.ForeignKey(Quote, related_name='quote_requote', null=True, blank=True)

'''-----------
	Signals
------------'''
@receiver(post_save, sender=ReQuote)
def requote_notification(sender, instance, created,**kwargs):
	if created:
		notifications = Notification(user=instance.quote.user, notif_type=1, notif_item=instance.quote.id, sender=instance.user)
		notifications.save()

quotes/views.py
 # -*- coding: utf-8 -*-
import json, hashlib, urllib
from django.conf import settings
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponse, Http404
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from social.backends.google import GooglePlusAuth
from quoffee.quotes.models import Notebook, Quote, ReQuote
from quoffee.users.models import Profile
from quoffee.context.models import Author, Category
from quoffee.tags.models import TagMap, Tag
from quoffee.utils.serializers import ReQuoteSerializer
from quoffee.utils.methods import generate_uniquekey, get_quote_display_data, get_quote_page_data, get_notebook_display_data, slugify_unique as slugify, get_is_user_context_data

# Create your views here.
def index(request):
    # scope = ' '.join(GooglePlusAuth.DEFAULT_SCOPE)
    # context = {
    #     'user': request.user,
    #     'plus_id': getattr(settings, 'SOCIAL_AUTH_GOOGLE_PLUS_KEY', None),
    #     'plus_scope': scope
    # }
    is_user = request.user.is_authenticated()
    if request.method=='GET':
        if request.GET.get('bm')=='on':
            if is_user:
                quote = request.GET.get('quote') if request.GET.get('quote') else ''
                url = request.GET.get('url') if request.GET.get('url') else ''
                profile = Profile.objects.get(user=request.user)
                notebooks = get_notebook_display_data(Notebook.objects.filter(user=request.user), profile.default_notebook)
                context_data = {
                        'quote': urllib.unquote(quote),
                        'url': url,
                        'notebooks': notebooks,
                        'profile': profile,
                        'categories': Category.objects.all().order_by('name'),
                        'is_bookmarklet': True,
                    }
                return render_to_response('bookmarklet/bookmarklet_dialog.html', context_data, RequestContext(request))
            else:
                return render_to_response('bookmarklet/bookmarklet_login.html', None, RequestContext(request))
        else:
            if is_user:
            	context_data = get_is_user_context_data(request.user)
                context_data['categories'] = Category.objects.all().order_by('name')
            else:
            	context_data = {'is_user': False}
            return render_to_response('index.html', context_data, RequestContext(request))
    else:
        raise Http404


def get_index_quotes(request):
    quotes = Quote.objects.filter(deleted=False, requoted=False).order_by('-added_date')[:70]
    quote_array = list()
    next_page = False
    p = Paginator(quotes, 10)
    try:
        this_page = int(request.GET.get('page')) if request.GET.get('page') else 1
        page_quotes = p.page(this_page)
        next_page = this_page+1 if page_quotes.has_next() else False
        for item in page_quotes:
            quote_array.append(get_quote_display_data(item))
    except (ValueError, EmptyPage, InvalidPage):
        pass
    context_data = {'quotes': quote_array, 'next_page': next_page, 'path': request.path}
    return render_to_response('quote-display-data.html', context_data, RequestContext(request))


def bookmarklet_page(request):
    if request.method == 'GET':
        is_user = request.user.is_authenticated()
        context_data = get_is_user_context_data(request.user) if is_user else {'is_user': False}
        return render_to_response('bookmarklet.html', context_data, RequestContext(request))
    else:
        raise Http404

def get_quote_page(request, uniquekey):
    public = True
    context_data = None
    is_user = request.user.is_authenticated()
    if request.method=='GET':
        if is_user:
            profile = Profile.objects.get(user=request.user)
            notebooks = get_notebook_display_data(Notebook.objects.filter(user=request.user), profile.default_notebook)
            user = dict(id=request.user.id, name=request.user.first_name+' '+request.user.last_name, display=profile.display, username=request.user.username)        
            tagmap = TagMap.objects.values_list('tag_id', flat=True).filter(quote__user=request.user)
            tags = Tag.objects.filter(id__in=tagmap)
            context_data = {'user': user, 'is_user': is_user, 'notebooks': notebooks, 'profile': profile,'tags': tags}        
        try:
            quote = Quote.objects.get(uniquekey=uniquekey, deleted=False)
            if context_data:
                context_data['data'] = get_quote_page_data(request.user, quote)
            else:
                context_data = {'data': get_quote_page_data(request.user, quote),'is_user': is_user}
        except Quote.DoesNotExist:
            quote_data = None
    else:
        context_data = None
    return render_to_response('quote-page.html', context_data, RequestContext(request))


def insert_quote(request):
    errors = list()
    message = None
    uniquekey = None
    if request.method == 'POST' and request.user.is_authenticated():
        profile = Profile.objects.get(user=request.user)
        form = request.POST
        #notebook stuff.
        is_new_notebook = False
        new_notebook_data = None
        selected_notebook = form.get('newnotebook')
        if selected_notebook and len(selected_notebook)>0:
            notebook_max_length = getattr(settings,'NOTEBOOK_NAME_LENGTH')
            selected_notebook = (selected_notebook[:notebook_max_length]) if len(selected_notebook) > notebook_max_length else selected_notebook
            if profile.notebook_count < profile.notebook_limit:
                notebook = Notebook(name=selected_notebook, user=request.user, uniquekey=generate_uniquekey(getattr(settings, 'NOTEBOOK_KEY_LENGTH')))
                notebook.save()
                profile.notebook_count = profile.notebook_count + 1
                profile.save()
                is_new_notebook = True
                new_notebook_data = {'id': notebook.id, 'name': notebook.name}
            else:
                errors.append("That's a bummer but you exceeded your notebook limit.")
        else:
            try:
                notebook = Notebook.objects.get(uniquekey=form.get("notebook"), user=request.user)
            except Notebook.DoesNotExist:
                errors.append("Hey. The selected notebook is not yours!")
        #category stuff.
        selected_category = form.get('category')
        if selected_category:
            try:
                if isinstance(int(selected_category), (int, long)):
                    try:
                        category = Category.objects.get(pk=selected_category)
                        custom_category = False
                    except Category.DoesNotExist:
                        errors.append('Sorry, but the last time we checked numbers are not categories.')
            except ValueError: # is not a integer.
                custom_category = True
        #author stuff.
        selected_author = form.get('author')
        author = None
        if selected_author:
            try:
                if isinstance(int(selected_author), (int, long)):
                    try:
                        author = Author.objects.get(pk=selected_author)
                    except Author.DoesNotExist:
                        errors.append('Sorry, but the last time we checked numbers are not authors.')
            except ValueError:
                    try:
                        author = Author.objects.get(name__iexact=selected_author)
                    except Author.DoesNotExist:
                        author = Author(name=selected_author, user=request.user)
                        author.save()
        #quote stuff
        if len(errors) == 0:
            quote = Quote(user=request.user,uniquekey=generate_uniquekey(getattr(settings, 'QUOTE_KEY_LENGTH')), author=author, notebook=notebook, text=form.get('text'))
            if selected_category:
                if custom_category:
                    quote.custom_category = selected_category
                else:
                    quote.category = category
            if form.get('url'):
                quote.url = form.get('url')
            quote.save()
            uniquekey = quote.uniquekey
            message = "Behold! You have a brand new quote!"
            if author:
                author.quote_count = author.quote_count + 1
                author.save()
                #save author quote log. here <----------------------------------------------------------------------------
            #tags stuff
            selected_tags = form.get('tags')
            if selected_tags:
                tags_array = selected_tags.split(',')
                for item in tags_array:
                    #search for an existing tag, if it does not exists, create a new one.
                    item = item.lower()
                    try:
                        tag = Tag.objects.get(name=item)
                    except Tag.DoesNotExist:
                        tag = Tag(name=item, user=request.user, slug=slugify(item,Tag))
                        tag.save()
                    tagmap = TagMap(tag=tag, quote=quote)
                    tagmap.save()
    else:
        errors.append("We are sorry but only authenticated users can create new quotes.")
    response = {'valid': (len(errors)==0), 'errors':errors, 'is_new_notebook': is_new_notebook, 'new_notebook_data': new_notebook_data, 'quotekey': uniquekey, 'message': message}
    json_response = json.dumps(response)
    return HttpResponse(json_response, content_type='application/javascript')


def delete_quote(request):
    errors = list()
    message = None
    if request.method=="POST" and request.user.is_authenticated():
        try:
            quote = Quote.objects.get(uniquekey=request.POST.get('key'), user=request.user)
            quote.deleted = True if not request.POST.get('undo') else False

templates/activation.html
{% extends "base.html" %}
{% load url from future %}
{% block extracss %}
<style type="text/css">
{% if flavour == 'full' %}
.content {	
	max-width: 800px;
	margin: 0 auto;
	margin-top: 100px;
}
p{
	font-size: 2em;
}
{% endif %}
</style>
{% endblock %}

{% block content %}
<div class="pure-u-1">
	<div class="content aligncenter">
		{% if error %}
			<p>There was something wrong with your activation request.</p>
		{% else %}
			<p>Great News! Your account has been activated! You can start quoting!</p>
		{% endif %}
	</div>
</div>
{% endblock %}

templates/base.html
<html>
	<title>{% block title %}{% endblock %}</title>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="mobile-web-app-capable" content="yes">
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
		<link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,900' rel='stylesheet' type='text/css'>
		<link type="text/css" rel="stylesheet" href="/static/css/jquery.mmenu.jd.css" />
		<link type="text/css" rel="stylesheet" href="/static/css/magnific-popup.css" />
		<link type="text/css" rel="stylesheet" href="/static/css/jquery.selectize.default.css" />

		<link type="text/css" rel="stylesheet" href="/static/css/jquery.easydropdown.css" />
	
		<link type="text/css" rel="stylesheet" href="/static/css/loadingbar.css" />
		<link type="text/css" rel="stylesheet" href="/static/css/messenger.css" />
		<link type="text/css" rel="stylesheet" href="/static/css/messenger-theme-air.css" />
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<link href="//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.css" rel="stylesheet">
		<link rel="shortcut icon" href="/static/images/app/app-logo-iDevice-greenbg.png">
		<link rel="apple-touch-icon-precomposed" href="/static/images/app/app-logo-iDevice-greenbg.png"/>
		<link rel="apple-touch-icon" href="/static/images/app/app-logo-iDevice-greenbg.png"/>
		<link rel="stylesheet" type="text/css" href="/static/css/app-base.css?t=1395980141">
		{% block extracss %}
		{% endblock %}
		<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery.mmenu.min.all.js"></script>
		<script type="text/javascript" src="//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.js"></script>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		  ga('create', 'UA-48821150-1', 'quoffee.com');
		  ga('send', 'pageview');
		</script>
	</head>
	<body>
		{% if is_user %}
		<div id="mymenu">
			<div>
				<div style="" class="quotemenu-header">
					<div class="circular-60 margin-auto" style="background: url({{ user.display }}) no-repeat; background-size:60px 60px; position:relative;">
						{% if notifications_count and notifications_count > 0 %}
						<a href="javascript:void(0);" class="side-notification-a" onclick="javascript:readAllNotifications();">
							<div class="side-notification" style="">
								<span class="side-notification-count">{{ notifications_count }}</span>
							</div>
						</a>
						{% endif %}
					</div>

					<label style="">{{ user.name }}</label>
					<label><a href="/logout" style="color:#cecece; text-decoration:none;">Logout</a></label>

				</div>
				<div class="menu-item">
					<span><i class="fa fa-home" style="margin-right:5px; color:#fff;"></i><a href="/" style="color:#fff; text-decoration:none;">Home</a></span>
				</div>
				{% if notebooks %}
				<div class="menu-item">
					<div style="position:relative; margin-bottom:10px;">
						<span style="font-weight:700; color:#fff;"><i class="fa fa-book"></i> 
							Notebooks   						
						</span>
						<div class="mm-quotemenu-options-1" style="top:0px; right:1px;">
							<span href="#notebook-form" name="notebook-new"><i class="fa fa-plus-circle"></i></span>
						</div>
					</div>
					<ul id="notebook-list" style="display:inline;">
						{% include "notebook-list.html" %}
					</ul>
				</div>
				{% endif %}
				{% if tags %}
				<div class="menu-item">
					<span style="font-weight:700; color:#fff;"><i class="fa fa-tag"></i> Tags</span>
					<ul id="tag-list">
						{% for item in tags %}
						<li><a href="/{{ user.username }}/tags/{{ item.slug }}">#{{ item.name }}</a></li>
						{% endfor %}
					</ul>
				</div>
				{% endif %}
			</div>
		</div>
		{% endif %}
		<div class="pure-g-r">
		{% if is_user %}
		<a href="#mymenu" id="menuLink" class="menu-link">
			<img src="/static/images/app/app-logo-green_40.png">
		</a>
		{% if notifications_count and notifications_count > 0 %}
		<a href="javascript:void(0);" onclick="javascript:readAllNotifications();">
			<div class="main-notification" style="">
				<span class="main-notification-count">{{ notifications_count }}</span>
			</div>
		</a>
		{% endif %}
		{% else %}
		<a class="menu-link" href="/">
			<img src="/static/images/app/app-logo-green_40.png">
		</a>
		{% endif %}

		{% block content %}

		{% endblock %}
		</div>
		<div class="footer">
			<ul>
				<li><a href="https://medium.com/quoffees-blog" target="_blank">Blog</a></li>
				<li><a href="/bookmarklet">Bookmarklet</a></li>
				<li><a href="/support">Help</a></li>
				<li><a href="/contact">Contact</a></li>
				<li><a href="http://www.twitter.com/getquoffee" target="_blank"><i class="fa fa-twitter fa-2x" ></i></a></li>
			</ul>
		</div>
		<!-- Quote form -->
		{% if profile.activated %}
			{% include "quote-form.html" %}
			{% include "quote-change-notebook-form.html" %}
		{% else %}
		<div id="new-quote" class="white-popup mfp-hide" data-activated="false">	
			<div>
				<p>We are deeply sorry but right now you can't create quotes. You have to activate your account first.</p>
				<p>If you lost your activation email or you didn't give us a real one check the F.A.Q. for directions.</p>
			</div>
		</div>
		{% endif %}
		<!-- End quote form -->
		<!-- Notebook Form -->
		<div id="notebook-form" class="notebook-popup mfp-hide">
			<form class="pure-form pure-form-stacked quote-form" id="form-notebookform">{% csrf_token %}
				<input type="hidden" id="notebookform-key" name="key">
			 	<label for="notebooform-name">Name</label>
        		<input id="notebookform-name" name="name" type="text" placeholder="Type the notebook name here.">
        		<button class="pure-button pure-button-success pure-u-1" id="btn-savenotebook">Save!</button>
			</form>
		</div>
		<!-- End Notebook Form -->

		<div id="quote-panel" class=""></div>

		<script type="text/javascript" src="/static/js/jquery.magnific-popup.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery.autosize.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery.selectize.min.js"></script>
		<script type="text/javascript" src="/static/js/jquery.easydropdown.js"></script>	
		<script type="text/javascript" src="/static/js/jquery.cookie.js"></script>	
		<script type="text/javascript" src="/static/js/messenger.min.js"></script>
		<script type="text/javascript" src="/static/js/waypoints.min.js"></script>		
		<script type="text/javascript" src="/static/app/commons.js"></script>

		<script type="text/javascript">
		/* urls */
		var url_users_search_profile = "{% url 'users:search_profile' %}";
		var url_quotes_get_data = "{% url 'quotes:get_quote_data' %}";
		var url_quotes_notebook_new = "{% url 'quotes:notebook_crud' 'new' %}";
		var url_quotes_notebook_edit = "{% url 'quotes:notebook_crud' 'edit' %}";
		var url_quotes_notebook_delete = "{% url 'quotes:notebook_crud' 'delete' %}";
		var url_quotes_notebook_default = "{% url 'quotes:notebook_crud' 'default' %}";
		var url_quotes_notebook_list = "{% url 'quotes:get_notebook_list' %}";
		var url_quotes_requote = "{% url 'quotes:requote' %}";
		var url_quotes_delete = "{% url 'quotes:delete_quote' %}";
		</script>
		<script type="text/javascript" src="/static/app/webapp.js?t=1395980141"></script>
		<script type="text/javascript" src="/static/app/quote-form.js"></script>
		<script type="text/javascript">
		{% if is_user %}
		$(document).ready(function(){
			getNotebookProfileData();
		});
		{% endif %}
		</script>
		{% block extrajs %}{% endblock %}
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=672961956099279";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		</script>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
		<script type="text/javascript" src="http://static.bufferapp.com/js/button.js"></script>
	</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}Quoffee - Contact{% endblock %}
{% block extracss %}
<style type="text/css">
.content{
	max-width: 800px;
	margin: 0 auto;
	padding: 2em 1em 1em 1em;
}


</style>
{% endblock %}

{% block content %}
<div class="pure-u-1">
	<div class="content">
		<div>
			<h1>Quoffee Contact Information</h1>
		</div>
		<div>
			<p>We'd love to hear from you. Please let us know what do you think of Quoffee.com, what features would you like us to build and how we can improve your experience using our product.</p>
			
				<p><a class="a-success" href="https://docs.google.com/forms/d/1bmewFEc5PXDF0QYolVPs1o1wxaYFjzK4KlXoRBrJbJo/viewform">Click to send direct feedback</a></p>
			
			<p>
				But if you prefer, you can send us an email at <a class="a-success" href="mailto:info@quoffee.com">info@quoffee.com</a> or <a class="a-success" href="http://www.twitter.com/getquoffee">tweet us</a>.
			</p>
		</div>
	</div>
</div>
{% endblock %}

templates/home.html
<html>
	<head>
	</head>
	<body>
		<h1>Authentication is done</h1>
	</body>
</html>

templates/login.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}Login{% endblock %}
{% block extracss %}
<style type="text/css">
{% if flavour == 'full' %}
.content {
	margin-top: 100px;
}
{% endif %}
</style>
{% endblock %}

{% block content %}
<div class="pure-u-1">
	<div class="content aligncenter">
		<div class="login-form">
			<h1>Sign in with...</h1>
			<h2>So we can add your Avatar and Name</h2>
			<p>We will never post without your permission</p>
			<div class="social-auth">
				<a href="{% url 'social:begin' 'twitter' %}"><img src="/static/images/social/signin-twitter.png"></a> <br />
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/quote-form.html
<div id="new-quote" class="white-popup mfp-hide" data-activated="true" style="position:relative;">
	<div class="loading-new-quote" style="display:none;">
		<div style="position: absolute; bottom:10px; right:10px;">
			<i class="fa fa-spinner fa-spin fa-2x"></i>
		</div>
	</div>
	<div style="">
		<div id="quote-errors" class="pure-error" style="margin:20px 0 20px 0; display:none;">
			<h4 style="margin:0;">Check errors bellow</h4>
			<div id="quote-errors-list">
			</div>
		</div>
		<form class="pure-form pure-form-stacked quote-form" id="form-newquote">{% csrf_token %}
			<div class="pure-u-1" style="margin: 0.5em 0;">
				<div class="pure-u-3-5" style="">
					<select id="quote-notebook" class="dropdown" name="notebook">
						{% for item in notebooks %}
							<option value="{{ item.uniquekey }}" {% if item.default %}selected{% endif %}>{{ item.name }}</option>
						{% endfor %}
					</select>
				</div>
				{% if not is_bookmarklet %}
				<div class="pure-u-1-5">
					<button class="pure-button pure-button-success pure-button-xlarge button-notebook" id="btn-newnotebook" style="">
						<i class="fa fa-plus"></i>
					</button>
					<button class="pure-button pure-button-success pure-button-xlarge button-notebook" id="btn-cancelnotebook" style="display:none;">
						<i class="fa fa-times"></i>
					</button>
				</div>
				{% endif %}
			</div>
			<br>
			{% if not is_bookmarklet %}
			<input type="text" id="quote-newnotebook" name="newnotebook" placeholder="New notebook name" style="display:none; margin: 0.5em 0;">
			{% endif %}
			<textarea id="quote-text" name="text" placeholder="My new awesome quote" required>{% if quote %}{{ quote }}{% endif %}
			</textarea>
			{% if is_bookmarklet %}
			<input type="hidden" id="quote-url" name="url" value="{% if url %}{{ url }}{% endif %}">
			{% endif %}
			<select id="quote-author" placeholder="Author" name="author"></select>
			<select placeholder="Select the category or create a new one" id="quote-category" name="category">
				<option></option>
				{% for item in categories %}
					<option value="{{ item.id }}">{{ item.name }}</option>
				{% endfor %}
			</select>				
			<input type="text" name="tags" id="quote-tags" placeholder="Tags (funny, tech, inspiring)"/>
			<br>
			<button class="pure-button pure-button-success pure-u-1" id="btn-insertquote" data-url="{% url 'quotes:insert_quote' %}" data-bookmarklet="{% if is_bookmarklet %}true{% else %}false{% endif %}">
				Post It
			</button>
		</form>
	</div>
</div>